### ISSUE TITLE
Can I please have all your private repos as an invatation

### ISSUE THREAD

**Issue by OrangeNickAnimate** [Windows81/GoAnimate-Character-Dump#4]

**Comment by OrangeNickAnimate** [comment]
Plz

**Comment by Windows81** [comment]
There's a thing that is said about the word 'plz'; that since it's shorter
than 'please', a 'no' would be more appropriate since it's shorter than
'yes'.

In the near future, when GoAnimate-Wrapper gets taken down for good, I
wouldn't be wanting others to host it themselves (give Copyright some
respect, that's why).  I've been thinking about whether I should continue
giving access to people who ask - even you.

For this reason, I'm not giving access away at this time.  Since the source
code has been leaked anyway, you could always ask friends who have a  copy
of it anyway.

Regards,
Ahmed Abo-Shadi

**Comment by OrangeNickAnimate** [comment]
Can you just give it to me

**Comment by Windows81** [comment]
I don't give away invitations anymore.
