### ISSUE TITLE
You need to convert the Legacy Video Maker from Flash to HTML5 before December 2020 Link:

### ISSUE THREAD

**Issue by bigstrongbear** [Windows81/GoAnimate-Character-Dump#6]
https://www.youtube.com/watch?v=0CIl3tOXV6s  https://www.youtube.com/watch?v=SIgW0SvP_6g&feature=emb_logo

**Comment by Windows81** [comment]
GoAnimate's LVM, unlike other Flash containers, can't simply be converted to a modern technology seamlessly.  That is because most SWF converters are only designed to extract basic video streams and repackage them as a standalone media players.  Besides: if you have the resources, *why don't you do it?*
